"""Remove unique constraint completely to allow same category in different periods

Revision ID: 005
Revises: 004
Create Date: 2025-08-13 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        # Drop the unique constraint completely to allow same category in different time periods
        batch_op.drop_constraint('uix_tariff_route_weight_no_dates', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        # Restore the constraint (though this might fail if data violates it)
        batch_op.create_unique_constraint(
            'uix_tariff_route_weight_no_dates', 
            ['origin_country', 'destination_country', 'goods_category', 'postal_service', 'min_weight', 'max_weight']
        )

    # ### end Alembic commands ###
