"""Update tariff rates unique constraint to include weight ranges

Revision ID: 3ba6a9d1f183
Revises: 001
Create Date: 2025-08-10 12:07:01.527414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba6a9d1f183'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_tariff_route_extended'), type_='unique')
        batch_op.create_unique_constraint('uix_tariff_route_weight_extended', ['origin_country', 'destination_country', 'goods_category', 'postal_service', 'start_date', 'end_date', 'min_weight', 'max_weight'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_tariff_route_weight_extended', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_tariff_route_extended'), ['origin_country', 'destination_country', 'goods_category', 'postal_service', 'start_date', 'end_date'])

    # ### end Alembic commands ###
